os:
  - linux
  - osx
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - "./autogen.sh"
  - "./configure"
before_script:
  # Allow us to SSH passwordless to localhost
  - ssh-keygen -t "rsa" -f ~/.ssh/id_rsa -N ""
  - cp ~/.ssh/{id_rsa.pub,authorized_keys}
script:
  - make
  - make test
  - make tar
deploy:
  provider: releases
  api_key:
    secure: vlYgJ2PWqfM1YA9Rw/qpJntaRl276uq8BcL7raDMNDySqO7QUg2TIilxWRxiiWLGjHUabAdsn8fsNEYmHfCLKywJdqzU90SS9KDWmSuVgzJfLBIPYlgfVMjEa0QQRZgJ7k1Oe2jsmH9lJuZw9jW/xG2C4eQRqAQ64m+UWwcDHqw=
  file: rsnapshot-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    # maybe we have to add rsnapshot-maintainers@lists.sourceforge.net
    # this will depend on activity and notification-settings
    recipients:
      - benedikt@heine.rocks
    on_success: change
    on_failure: always
